# Generated by Django 3.2 on 2021-06-02 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_category_category_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_brand', models.CharField(max_length=50)),
                ('product_name', models.CharField(max_length=150)),
                ('product_price', models.IntegerField()),
                ('product_discount', models.IntegerField(default=0)),
            ],
        ),
    ]
