# Generated by Django 3.2 on 2021-06-02 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_cart_quantity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cart',
        ),
    ]
