# Generated by Django 3.2 on 2021-06-07 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_order_orderitems'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderItems',
            new_name='OrderItem',
        ),
        migrations.AlterField(
            model_name='order',
            name='date_added',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='time_added',
            field=models.TimeField(),
        ),
    ]
