# Generated by Django 3.2 on 2021-06-07 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_address_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='pincode',
            field=models.CharField(max_length=6),
        ),
    ]
