# Generated by Django 3.2 on 2021-06-09 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0030_alter_order_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
    ]
