# Generated by Django 3.2 on 2021-06-09 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0031_remove_order_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
