# Generated by Django 3.2 on 2021-06-10 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0036_auto_20210609_2149'),
    ]

    operations = [
        migrations.CreateModel(
            name='tips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('title', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('P', 'Publish')], max_length=20, null=True)),
            ],
        ),
    ]
